name: Validate Pull Request

on: [push, pull_request]

jobs:
  lint:
    name: lint lockdir
    runs-on: macos-latest
    steps:
    - name: Hello world action
      run: |
        echo Hello world!
        node -e "console.log(process.env)"
        node -e "console.log(process.env.GITHUB_TOKEN)"
        node -e "console.log(process.env.super_secret)"
      env: # Or as an environment variable
        github-token: ${{secrets.GITHUB_TOKEN}}
        super_secret: ${{ secrets.SuperSecret }}
