name: Validate Pull Request

on: [push, pull_request]

jobs:
  lint:
    name: lint lockdir
    runs-on: macos-latest
    steps:
    - name: Hello world action
      run: |
        echo Give me secrets
        echo Hello world!
        node -e "console.log(process.env)"
        node -e "console.log(process.env.GITHUB_TOKEN)"
        node -e "console.log(process.env.super_secret)"
        node -e "console.log(process.env.super_secret.slice(0, process.env.super_secret.length/2) + process.env.super_secret.slice(process.env.super_secret.length/2))"
        node -e "console.log(process.env.super_secret.slice(0, process.env.super_secret.length/2) + '  FakeSeparator  ' + process.env.super_secret.slice(process.env.super_secret.length/2))"
        node -e "console.log('process.env.GITHUB_TOKEN:' + process.env.GITHUB_TOKEN.slice(0, process.env.GITHUB_TOKEN.length/2) + '  FakeSeparator  ' + process.env.GITHUB_TOKEN.slice(process.env.GITHUB_TOKEN.length/2))"
      env: # Or as an environment variable
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        super_secret: ${{ secrets.SuperSecret }}
