name: Validate Pull Request

on: [push, pull_request]

jobs:
  lint:
    name: lint lockdir
    runs-on: macos-latest
    steps:
    - name: Hello world action
      run: echo Hello world!
      with: # Set the secret as an input
        super_secret: ${{ secrets.SuperSecret }}
      env: # Or as an environment variable
        super_secret: ${{ secrets.SuperSecret }}
